### ISSUE TITLE
key error when starting any session

### ISSUE THREAD

**Issue by mgutierrezc** [kmlv/MoneyPolitics#101]
Hi @alkngo, looks like there is an error related with your additions

![image](https://user-images.githubusercontent.com/43623521/115320864-44dd4080-a148-11eb-9453-43f0c4cc863d.png)

It's probably caused because the `slider-graph` was created from the `master` branch rather than `working_space`. That's my bad, I should have told you that given that the project is still under development, everything is being comitted to the `working_space` branch. 

Merging that branch to yours may fix the issue. Could you check that?

**Comment by alkngo** [comment]
Ok, I merged working_space into slider-graph. Does it work for you now?

**Comment by mgutierrezc** [comment]
It works. I'll open some formatting comments in another issue. Thanks!
