### ISSUE TITLE
Incorporate Slider into Experiment

### ISSUE THREAD

**Issue by mgutierrezc** [kmlv/MoneyPolitics#103]
The slider should replace this table on the page `TaxRateParameter` and should store the chosen tax rate in the player field `tax_rate`
![image](https://user-images.githubusercontent.com/43623521/118604974-65b2a900-b77b-11eb-9fb4-80a965ce7504.png)

**Comment by alkngo** [comment]
Ok, @mgutierrezc I finished integrating the slider into that page. It's up the `slider-graph` branch now

**Comment by mgutierrezc** [comment]
It's working great. There is just a small issue regarding rounding: 
![image](https://user-images.githubusercontent.com/43623521/118917284-1d6bc600-b8f6-11eb-9518-8e3a0bed1033.png)

**Comment by alkngo** [comment]
Ok, I pushed a change that should round the decimal tax rates.

**Comment by mgutierrezc** [comment]
Cool! Instead of displaying "endowment_{value}", could we display "Endowment {value}" for both legend and tooltips?
![image](https://user-images.githubusercontent.com/43623521/119444351-b3d22a00-bcf0-11eb-9ced-970799b7cb6e.png)
Thanks!

**Comment by alkngo** [comment]
Ok just updated it. Does it look good now?

**Comment by mgutierrezc** [comment]
Could you make the legend a bit smaller so that it doesn't overlaps with the Y axis?
![SCREEN probs legend](https://user-images.githubusercontent.com/43623521/119539608-fc6dff80-bd51-11eb-85f8-30ea370d027d.png)

**Comment by mgutierrezc** [comment]
Now that's finally done, would you create a pull request for merging this to `working_space`?

**Comment by alkngo** [comment]
Ok, done
