### ISSUE TITLE
Slider without tick required

### ISSUE THREAD

**Issue by mgutierrezc** [kmlv/MoneyPolitics#11]
In case this takes too long, use:

- Drop-down menu
- Radio buttons

**Comment by mgutierrezc** [comment]
Couldn't find slider w/o tick. I'll probably use Radio Buttons

**Comment by johnjelliott** [comment]
Sounds good to me

**Comment by mgutierrezc** [comment]
Do you remember if Kristian wanted them to be Horizontal?

**Comment by johnjelliott** [comment]
I think he only cared that all options appeared simultaneously. So if there
are two rows that might be an issue. I think having all options horizontal
is probably safest.
