### ISSUE TITLE
Identifier for same income players required in ReceivingMessage

### ISSUE THREAD

**Issue by mgutierrezc** [kmlv/MoneyPolitics#17]
Currently, the code doesn't add one when receiving a message from players of the same income

**Comment by johnjelliott** [comment]
Can you explain the "add one" idea? Is it that the code doesn't count messages sent to players of the same income as costly?

**Comment by mgutierrezc** [comment]
Sure. When a player receives a message, the code is not adding a `#1` or `#2` label when displaying messages of senders who have the same income. I'll work on a way to figure that out during the week
