### ISSUE TITLE
Progressivity presentation for players

### ISSUE THREAD

**Issue by mgutierrezc** [kmlv/MoneyPolitics#26]
Search for an easy way in which players understand how each level of progressivity works

**Comment by johnjelliott** [comment]
I will spend time on this today

**Comment by mgutierrezc** [comment]
Actually, I'm working on this one. I'll push what I've done about it later today

**Comment by mgutierrezc** [comment]
Already pushed to my branch. Check the folder `progressivity_pres`. Inside,  you'll find a Jupyter notebook with my first proposal for the progressivity levels display. I'll add my second one between today and tomorrow

**Comment by johnjelliott** [comment]
Okay sounds good!

**Comment by mgutierrezc** [comment]
Finished. I'm going to push and make a pull request with the files for the progressivity displays
