### ISSUE TITLE
Search for public code on custom chat box

### ISSUE THREAD

**Issue by mgutierrezc** [kmlv/MoneyPolitics#29]
- [x] Look for a way to implement it
- [x] Do the implementation

**Comment by mgutierrezc** [comment]
Found sth:

https://github.com/RoboAndie/django-countable-field

But raises this error when implementing it:

`NameError: name 'self' is not defined`

I've posted about it on the oTree Google Group, so we could wait a bit for an answer:
https://groups.google.com/g/otree/c/-A2gfeGvCx8

**Comment by johnjelliott** [comment]
Sounds good thanks

**Comment by mgutierrezc** [comment]
I'll be implementing the suggested solution 

```
{% formfield player.message %}
<p><span id="char-count">0</span>/1000 characters</p>

<script>
let charcount = document.getElementById('char-count')
let messageInput = document.querySelector('[name=message]');
messageInput.oninput = function() {
charcount.innerText = messageInput.value.length;
};
</script>
```
