### ISSUE TITLE
Update settings/code for treatment variables

### ISSUE THREAD

**Issue by mgutierrezc** [kmlv/MoneyPolitics#31]
- [x] Add treatment vars: messaging costs, type of message, type of randomness
- [ ] Prepare the code for new treatment vars

**Comment by mgutierrezc** [comment]
@johnjelliott , when you update the settings, take in account the `SESSION_CONFIGS` value from the README file pls. I changed it so that we have a Test (2 players) and a Production (9 players) sessions.

**Comment by johnjelliott** [comment]
I have created variables inside the session config but I will try to create another configured session so we don't have to change each variable

**Comment by mgutierrezc** [comment]
Cool. Use a unique ‘display_name’ entry per session config, sth like “Money Politics - Treatment Var 1 x Treatment Var 3”

**Comment by johnjelliott** [comment]
I created them in a very similar though process but if they don't feel intuitive to you then I can easily change them.  You can see the changes in my branch README for now, I am going to work on more code integration with the settings before adding a pull request for the working space

**Comment by mgutierrezc** [comment]
- Sth I erased from the `SESSION_CONFIGS` dict's were the following entries:

```
        # Display player ID
        # 'show_id': True,
        # Display player income
        # 'show_income': True,
        # Which game will be played (Tetris or Diamonds)
        # 'treatment': "Tetris",
```

Previously, those were treatment vars, but now they are only ctrls. I've adapted the code for that in my latest Pull Req. Could you update the settings for this change pls?

- About the Session Config dict's, could you have a `display_name` entry in them? For example, the test config had this entry before `"Money Politics (Test)"`. We should have sth very similar for the rest of configs to make them more understandable
