### ISSUE TITLE
Move explanation of sending section to instructions 

### ISSUE THREAD

**Issue by mgutierrezc** [kmlv/MoneyPolitics#9]

**Comment by mgutierrezc** [comment]
@johnjelliott  don't do this yet. I'm adding some translation option to this page. I'll add a new comment as soon as I finish with that feature so that you can complete this task

**Comment by mgutierrezc** [comment]
Done. You can continue with this. Thanks!

**Comment by johnjelliott** [comment]
Yes, no problem, I will be getting all my tasks done over the weekend, as I
have been caught up in a huge workload this week.
